sonar.organization=python-app
sonar.projectKey=python-app

# relative paths to source directories. More details and properties are described
# at https://docs.sonarsource.com/sonarqube-cloud/advanced-setup/analysis-scope/
sonar.sources=backend,ui